site_name: Hanzo Garden
site_url: https://garden.hanzo.page/ # must have the trailing slash
site_author: Peter Hanzo
site_description: Cloud Tools for your productivity
repo_name: peter-hanzo/Digital-Garden/
repo_url: https://github.com/peter-hanzo/garden/
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site

copyright: > # should remain a link to the original theme
     2021-2023 <br>
     🔰 <a href="https://peter.hanzo.page">Peter Hanzo</a>  <br>
     
     


# Theme settings
#
theme:
  # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
  name: material
  logo: assets/ava-40.svg
  favicon: assets/ava-favicon.png
  icon:
    admonition:
      notes: octicons/list-unordered-16
      abstract: octicons/server-16
      info: octicons/link-16
      tip: octicons/report-16
      question: octicons/question-16
      warning: octicons/alert-16
      danger: octicons/zap-16
      example: octicons/beaker-16
      quote: octicons/comment-discussion-16
      failure: octicons/x-circle-16
      video: octicons/device-camera-video-16
      success: octicons/issue-closed-16
      
  # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  custom_dir: overrides
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Inter
    code: Noto Sans
    # Noto Sans, Spectral, -apple-system, Inter,Helvetica Neue,Helvetica, Roboto
    # IMB Plex Mono, Cascadia, Roboto Mono
  language: en
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    # P
    # Light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: deep orange
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
      # P       
      # Dark mode    
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: Switch to light mode

  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    # - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level folders are shown as tabs
    # - navigation.tabs.sticky # tabs always show
    # - navigation.sections # second-level folders are expanded
    # - navigation.expand # all folders are expanded
    - navigation.indexes # link an index page to its parent folder
    - navigation.top # show the back-to-top button
    # - toc.integrate # show the table of contents in the navigation panel
    - navigation.tabs.sticky
    - navigation.instant
    - content.action.edit
    - content.action.view
  
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button of the current search

    # Header
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/
    - header.autohide # hide the post title when scroll down

    # Content
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate # add comment to code blocks
    - content.tabs.link # link tabs with the same label
    
    
  include_search_page: true
  earch_index_only: true
#
# Plugins
#
plugins:
  - search 

  - git-revision-date-localized:
        type: custom
        custom_format: "%d %B %Y"
        timezone: Europe/Amsterdam
        locale: en
        fallback_to_build_date: true
        enable_creation_date: false
        exclude:
            - index.md
            - tags.md


       

  - tags:
      tags_file: Tags.md
      
  - social:
      cards_font: Roboto
      cards_color:
        fill: "#7cf7cc" 
        text: "#252626"     


  
  - literate-nav:
      nav_file: SUMMARY.md

  - callouts
  # блоки советов!  
  
  # новые !!!!!!xcxc

  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true 
  - ezlinks
  - mermaid2

  - embed_file:
      callouts: true
      language_message: 'file not exists.'
      custom-attributes: 'assets/css/custom_attributes.css'
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - meta-descriptions
        
        
        
        


# Extensions
#
markdown_extensions:
  #
  # Python Markdown
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  #
  - meta
  - abbr # add a small tooltip to elements
  - admonition # add call-out blocks
  - attr_list # allow to add HTML attributes and CSS classes
  - def_list # add description lists
  - footnotes # define inline footnotes
  - meta # attach arbitrary key-value pairs to a document
  - md_in_html # allow to write Markdown inside HTML elements
  - tables # create tables in Markdown
  
  - toc: # generate a table of contents from documents
      permalink: '#' # anchor
      toc_depth: 4 # header 1 to header 4
      slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
  - sane_lists # make better lists
  - smarty: # convert some special characters
      smart_angled_quotes: true


# новые нужны!!!!!!
  - codehilite
  - nl2br
#разрывы строк
  - mdx_breakless_lists 
#для встроенных из обсидиан
  - def_list

  

  #
  # Python Markdown Extensions
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  #
  #- pymdownx.arithmatex: # render math equations
  #    generic: true
  # - pymdownx.betterem: # improve the detection of Markup to emphasize text in Markdown
      # smart_enable: all
  - pymdownx.caret # define superscript
  - pymdownx.mark # highlight text
  - pymdownx.tilde # define subscript
  - pymdownx.critic # track changes
  - pymdownx.details # add collapsible call-outs
  - pymdownx.emoji: # add inlines bundled and custom icons and emojis 
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences: # define code blocks and nesting of code
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight: # highlight of code blocks
      linenums_style: pymdownx-inline
      use_pygments: true
      anchor_linenums: true
      # anchor_linenums: true # create anchor link on each line of code
  - pymdownx.inlinehilite # highlight inline code blocks
  - pymdownx.smartsymbols # convert some sequences of characters into their corresponding symbols
  - pymdownx.snippets: #  embed content from arbitrary files into a document
  - pymdownx.tabbed: # group related content and code blocks under accessible tabs
      alternate_style: true
  - pymdownx.tasklist: # define list of task with checkbox
      custom_checkbox: true
  #- pymdownx.escapeall:
  #    hardbreak: true # use \ to create new line
  #    nbsp: true # use \<space> to create &nbsp;
  - pymdownx.keys # syntax ++ctrl+c++ does not look clear in MD document
  #- pymdownx.progressbar
  - mdx_truly_sane_lists
  
  
# проверить потом
  # Overview

  # SaneHeaders   
  #
  # Extra extensions

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
  analytics:
    provider: google
    property: G-G5YR725YTF
    # property: UA-42618265-2
  
  
  
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer
  social:
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/peter_hanzo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rudenkopeter/  
      
      
      
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/peter.hanzo/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/peter.hanzo.life/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peter_hanzo


    #- icon: fontawesome/brands/youtube
    #  link: https://www.youtube.com/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/peter-hanzo
    - icon: fontawesome/solid/envelope
      link: mailto:<peter@hanzo.page>
  
  generator: true # hide the line "Made with Material for MkDocs"

  hooks:
    strip_comments: false
    fix_heading: false
    
# Custom styles and scripts
#
extra_css:
  - assets/css/view-bigimg.css
  - assets/css/extra2.css
  - assets/css/template/grid.css
  - assets/css/custom_attributes.css
#  - assets/css/customization.css
  
  - assets/css/highlight.css



extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/view-bigimg.js
  - assets/js/extra.js
  

# новые!!!!!!❤️

  - assets/js/wiki_hover.js
  